# -*- coding: utf-8 -*-
"""Signal Processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnaPSA_igUW0czHzXAmOkh_Y0f4SUSP_
"""

!pip install numpy scipy pandas matplotlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.signal import butter, filtfilt, lfilter, welch, detrend, find_peaks
from scipy.fft import rfft, rfftfreq

fs = 25  # wearable sampling rate in Hz
duration = 120  # seconds
t = np.arange(0, duration, 1/fs)

true_hr_bpm = 78
true_hr_hz = true_hr_bpm / 60

# Clean PPG-like signal
ppg_clean = (
    1.0 * np.sin(2 * np.pi * true_hr_hz * t)
    + 0.35 * np.sin(2 * np.pi * 2 * true_hr_hz * t)
)

# Baseline drift
baseline = 0.5 * np.sin(2 * np.pi * 0.15 * t)

# High-frequency noise
noise = 0.15 * np.random.randn(len(t))

# Motion artifact around 1.8 Hz
motion_artifact = 0.6 * np.sin(2 * np.pi * 1.8 * t)

# Final noisy PPG
ppg = ppg_clean + baseline + noise + motion_artifact

plt.figure(figsize=(12, 4))
plt.plot(t[:500], ppg[:500], label="Noisy PPG")
plt.plot(t[:500], ppg_clean[:500], label="Clean PPG", alpha=0.8)
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.title("Synthetic PPG Signal")
plt.legend()
plt.grid(True)
plt.show()

ppg_detrended = detrend(ppg)

plt.figure(figsize=(12, 4))
plt.plot(t[:500], ppg[:500], label="Original PPG")
plt.plot(t[:500], ppg_detrended[:500], label="Detrended PPG")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.title("Detrending")
plt.legend()
plt.grid(True)
plt.show()

def butter_bandpass_filter(signal, fs, lowcut=0.5, highcut=4.0, order=4):
    b, a = butter(
        order,
        [lowcut, highcut],
        btype="bandpass",
        fs=fs
    )
    filtered = filtfilt(b, a, signal)
    return filtered, b, a

ppg_filtered, b, a = butter_bandpass_filter(
    ppg_detrended,
    fs=fs,
    lowcut=0.5,
    highcut=4.0,
    order=4
)

plt.figure(figsize=(12, 4))
plt.plot(t[:500], ppg_detrended[:500], label="Detrended")
plt.plot(t[:500], ppg_filtered[:500], label="Band-pass filtered")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.title("0.5–4 Hz Butterworth Band-pass Filter with filtfilt")
plt.legend()
plt.grid(True)
plt.show()

ppg_lfilter = lfilter(b, a, ppg_detrended)
ppg_filtfilt = filtfilt(b, a, ppg_detrended)

plt.figure(figsize=(12, 4))
plt.plot(t[:300], ppg_detrended[:300], label="Original detrended", alpha=0.5)
plt.plot(t[:300], ppg_lfilter[:300], label="lfilter: phase delay")
plt.plot(t[:300], ppg_filtfilt[:300], label="filtfilt: zero phase")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.title("lfilter vs filtfilt")
plt.legend()
plt.grid(True)
plt.show()

def estimate_hr_fft(signal, fs, low=0.5, high=4.0):
    n = len(signal)
    freqs = rfftfreq(n, d=1/fs)
    spectrum = np.abs(rfft(signal))

    mask = (freqs >= low) & (freqs <= high)

    peak_freq = freqs[mask][np.argmax(spectrum[mask])]
    bpm = peak_freq * 60

    return bpm, freqs, spectrum

bpm_fft, freqs_fft, spectrum_fft = estimate_hr_fft(ppg_filtered, fs)

print(f"Estimated HR using FFT: {bpm_fft:.2f} BPM")

plt.figure(figsize=(10, 4))
plt.plot(freqs_fft, spectrum_fft)
plt.xlim(0, 5)
plt.xlabel("Frequency (Hz)")
plt.ylabel("Magnitude")
plt.title("FFT Spectrum")
plt.grid(True)
plt.show()

def estimate_hr_welch(signal, fs, low=0.5, high=4.0, nperseg=256):
    freqs, psd = welch(signal, fs=fs, nperseg=nperseg)

    mask = (freqs >= low) & (freqs <= high)

    peak_freq = freqs[mask][np.argmax(psd[mask])]
    bpm = peak_freq * 60

    return bpm, freqs, psd

bpm_welch, freqs_welch, psd = estimate_hr_welch(ppg_filtered, fs)

print(f"Estimated HR using Welch PSD: {bpm_welch:.2f} BPM")

plt.figure(figsize=(10, 4))
plt.semilogy(freqs_welch, psd)
plt.xlim(0, 5)
plt.xlabel("Frequency (Hz)")
plt.ylabel("PSD")
plt.title("Welch Power Spectral Density")
plt.grid(True)
plt.show()

def estimate_hr_peaks(signal, fs, min_bpm=40, max_bpm=200):
    min_distance = int(fs * 60 / max_bpm)

    peaks, properties = find_peaks(
        signal,
        distance=min_distance,
        prominence=np.std(signal) * 0.4
    )

    peak_times = peaks / fs

    if len(peak_times) < 2:
        return np.nan, peaks

    ibi = np.diff(peak_times)
    bpm = 60 / np.mean(ibi)

    return bpm, peaks

bpm_peaks, peaks = estimate_hr_peaks(ppg_filtered, fs)

print(f"Estimated HR using peak detection: {bpm_peaks:.2f} BPM")

plt.figure(figsize=(12, 4))
plt.plot(t[:1000], ppg_filtered[:1000], label="Filtered PPG")
visible_peaks = peaks[peaks < 1000]
plt.plot(t[visible_peaks], ppg_filtered[visible_peaks], "o", label="Detected peaks")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.title("PPG Peak Detection")
plt.legend()
plt.grid(True)
plt.show()

def sliding_window_hr(signal, fs, window_sec=8, step_sec=2):
    window_size = int(window_sec * fs)
    step_size = int(step_sec * fs)

    results = []

    for start in range(0, len(signal) - window_size + 1, step_size):
        end = start + window_size
        segment = signal[start:end]

        bpm_welch, _, _ = estimate_hr_welch(
            segment,
            fs=fs,
            low=0.5,
            high=4.0,
            nperseg=min(256, len(segment))
        )

        results.append({
            "start_time": start / fs,
            "end_time": end / fs,
            "bpm": bpm_welch
        })

    return pd.DataFrame(results)

hr_df = sliding_window_hr(ppg_filtered, fs, window_sec=8, step_sec=2)

hr_df.head()

plt.figure(figsize=(12, 4))
plt.plot(hr_df["end_time"], hr_df["bpm"], marker="o")
plt.xlabel("Time (s)")
plt.ylabel("Estimated BPM")
plt.title("Window-based Heart Rate Estimation")
plt.grid(True)
plt.show()

def ppg_to_bpm_pipeline(ppg_signal, fs=25):
    # Step 1: detrend
    x = detrend(ppg_signal)

    # Step 2: bandpass filter
    x_filtered, _, _ = butter_bandpass_filter(
        x,
        fs=fs,
        lowcut=0.5,
        highcut=4.0,
        order=4
    )

    # Step 3: FFT estimate
    bpm_fft, _, _ = estimate_hr_fft(x_filtered, fs)

    # Step 4: Welch estimate
    bpm_welch, _, _ = estimate_hr_welch(x_filtered, fs)

    # Step 5: peak estimate
    bpm_peaks, peaks = estimate_hr_peaks(x_filtered, fs)

    return {
        "filtered_signal": x_filtered,
        "bpm_fft": bpm_fft,
        "bpm_welch": bpm_welch,
        "bpm_peaks": bpm_peaks,
        "peaks": peaks
    }

result = ppg_to_bpm_pipeline(ppg, fs=25)

print("FFT BPM   :", result["bpm_fft"])
print("Welch BPM :", result["bpm_welch"])
print("Peaks BPM :", result["bpm_peaks"])

# Simulated accelerometer reference correlated with motion artifact
acc_x = motion_artifact + 0.1 * np.random.randn(len(t))
acc_y = 0.5 * motion_artifact + 0.1 * np.random.randn(len(t))
acc_z = 0.2 * motion_artifact + 0.1 * np.random.randn(len(t))

acc_mag = np.sqrt(acc_x**2 + acc_y**2 + acc_z**2)

plt.figure(figsize=(12, 4))
plt.plot(t[:500], ppg[:500], label="Noisy PPG")
plt.plot(t[:500], acc_mag[:500], label="Accelerometer magnitude", alpha=0.8)
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.title("PPG and Accelerometer Motion Reference")
plt.legend()
plt.grid(True)
plt.show()

def nlms_filter(primary_signal, reference_signal, filter_order=8, mu=0.1, eps=1e-6):
    """
    primary_signal: noisy PPG = clean PPG + motion artifact
    reference_signal: accelerometer-derived motion reference

    returns:
    cleaned_signal: primary_signal - estimated_motion
    estimated_noise: estimated motion artifact
    """

    n_samples = len(primary_signal)

    w = np.zeros(filter_order)
    estimated_noise = np.zeros(n_samples)
    cleaned_signal = np.zeros(n_samples)

    for n in range(filter_order, n_samples):
        x = reference_signal[n-filter_order:n][::-1]

        y = np.dot(w, x)
        e = primary_signal[n] - y

        norm_factor = np.dot(x, x) + eps
        w = w + (mu / norm_factor) * e * x

        estimated_noise[n] = y
        cleaned_signal[n] = e

    return cleaned_signal, estimated_noise

ppg_nlms_cleaned, estimated_motion = nlms_filter(
    primary_signal=ppg,
    reference_signal=acc_mag,
    filter_order=16,
    mu=0.2
)

ppg_nlms_cleaned_filtered, _, _ = butter_bandpass_filter(
    detrend(ppg_nlms_cleaned),
    fs=fs,
    lowcut=0.5,
    highcut=4.0,
    order=4
)

plt.figure(figsize=(12, 4))
plt.plot(t[:500], ppg[:500], label="Noisy PPG", alpha=0.6)
plt.plot(t[:500], ppg_nlms_cleaned[:500], label="After NLMS")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.title("Motion Artifact Removal using NLMS")
plt.legend()
plt.grid(True)
plt.show()

before = ppg_to_bpm_pipeline(ppg, fs=25)
after = ppg_to_bpm_pipeline(ppg_nlms_cleaned, fs=25)

print("True HR BPM:", true_hr_bpm)
print()
print("Before NLMS")
print("FFT   :", before["bpm_fft"])
print("Welch :", before["bpm_welch"])
print("Peaks :", before["bpm_peaks"])

print()
print("After NLMS")
print("FFT   :", after["bpm_fft"])
print("Welch :", after["bpm_welch"])
print("Peaks :", after["bpm_peaks"])

